name: Build

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set version from tag
        shell: bash
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          npm version $TAG --no-git-tag-version
      - run: npm install
      - run: npm run build
      - run: npx electron-builder --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set version from tag
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          npm version $TAG --no-git-tag-version
      - run: npm install
      - run: npm run build
      - run: npx electron-builder --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}